application-research/autoretrieve

go.mod, go.sum
Fix the issue of segfaults getting generated from go-libp2p
- this is pulling in an as yet unmerged branch from a libp2p dependency. if it works we need to deploy a permaneant fix in a subsequence pr
- auto retrieve still seems like a low impact place to test this in production (lotus itself is now held up on fixing this bug)
=> Libp2p fix for segfault bug

go.mod, go.sum
This shouldn't have any effect -- just gets us off the weird transport upgrader branch.
=> Update libp2p and deps to tagged versions

main.go
Logs still showing resource limits exceeded shortly before peer resets that are causing paid retrievals to fail :( For now the simple solution is to disable the resource manager.
We need a long term strategy for dealing with these issues in the resource manager.
=> Disable the resource manager for now

README.md, bitswap/provider.go, main.go
Adds a CID blacklist for preventing configured CIDs from being retrieved from storage providers.
This implementation specifically checks if the CID is in the blacklist before looking it up in the blockstore, and then responds with a DONT_HAVE if the CID is found in the blacklist.
The existing miner white and black list commands, functions, and variables were prefixed with the word "miner" where necessary to easily differentiate between the miner and CID lists.
The command option `--cid-blacklist value` was added, mimicking the behavior of the `--miner-whitelist` and `--miner-blacklist` options.
The sub command `check-cid-blacklist` was added, mimicking the behavior of the `check-miner-whitelist` and `check-miner-blacklist` sub commands.
=> Add CID blacklist

.github/workflows/ecr-publisher.yml
Set up GitHub action job to build and publish the autoretrieve container
image to a repository set up in ECR at storetheindex AWS account.
The image tag is determined based on the build trigger: either merge to
`master` or publication of a GitHub release.
If the build is triggered from merge to `main`, then the tag will follow
`timestamp-<commit-sha>` format. The rationale for this for mat is to
have some monotonically increasing numerical valu in the tag so that the
tags can be sortable by age. This is then used by Flux CD to determine
whether there is a new container image available for automated
deployment.
Otherwise, the release name is expected to be a semver starting with `v`
and the tag will be set to the semantic version stripping off the `v`
prefix.
=> Automate container image build and publish to ECR

.github/workflows/cd.yml, deploy/manifests/base/config.yaml, deploy/manifests/base/deployment.yaml, deploy/manifests/base/kustomization.yaml, deploy/manifests/base/peerkey.encrypted, deploy/manifests/base/service.yaml, deploy/manifests/dev/us-east-2/.sops.yaml, deploy/manifests/dev/us-east-2/kustomization.yaml, deploy/manifests/dev/us-east-2/monitor.yaml, deploy/manifests/dev/us-east-2/peerkey.encrypted, deploy/manifests/dev/us-east-2/service-patch.yaml
Define the base K8S manifests along with placeholder for encrypted peer
identity. Define an overlay for `dev` `us-east-2` deployment to
storetheindex cluster.
The Peer ID is randomly generated and encrypted using `sops` which is
unencrypted on the fly at runtime by flux CD mechanism.
A service is defined to serve libp2p requests on port `6746`. This
service will use an AWS NLB with dns name `autoretrieve.dev.cid.contact`
in the dev overlay.
Pods' `/metrics` HTTP endpoint is monitored over port 8080 and metrics
are forwarded to `storetheindex-dev` Prometheus data source at
PL grafana. Logs are also automatically forwarded and should be aviable
at PL grafana provisioned Loki soruce, named
`grafanacloud-protocollabs-logs`.
A CI job is introduced to automatically create a PR for any new …
=> Define application level manifests and dev deployment overlay

deploy/manifests/base/config.yaml
Set prune to 15 GB for now until the requirements for disk size are
determined.
=> Set prune level to avoid pod being killed due to excessive disk usage

deploy/manifests/base/config.yaml, deploy/manifests/dev/us-east-2/deployment-patch.yaml, deploy/manifests/dev/us-east-2/kustomization.yaml, deploy/manifests/dev/us-east-2/pvc.yaml
The dev instance is consistently evicted because it overuses the maximum
available ephemeral storage. Assign a dedicated PVC to the running
instance with the size of 50 GiB to avoid the pod being killed.
=> Assign a dedicate PVC for cache with size 50GiB

.github/workflows/cd.yml
The CI job that creates PRs from the `cd/dev` branch is triggered on
push. If a push is made to those branches where the is no commit from
the main branch to create a PR the build will fail.
Check the error message for a case where the CD branch is pushed to but
has no commits ahead of the main branch and gracefully terminate the
build.
=> Do not create a PR in CD branches if there is no commit

filecoin/retriever.go, go.mod, go.sum
Implement filclient retrieval subscriber into autoretrieve.
I was waffling on creating a new struct for the subscriber, but there currently isn't any additional state that needs to be retained, so I opted for making the retriever struct the subscriber.
=> feat: subscribe to filclient retrieval events

Makefile
As long as we're not relying on submodules, let's go whole-hog and get the Makefile to make sure we're in sync and fix it up if it's not. Arguably not as necessary with `clean` removing `extern`, but this should be helpful for dev & testing when it's in flux as it adds rev check to each run.
=> build: make Makefile keep extern/filecoin-ffi properly in sync

main.go
Discovered after trying to run `gen-config` post Docker usage which had my ~/.autoretrieve owned by root so unwritable but silently failing.
With this change I get:
```
2022-07-14T11:40:45.299+1000    FATAL   autoretrieve    autoretrieve/main.go:105        open /home/rvagg/.autoretrieve/config.yaml: permission denied
```
=> fix: return errors from WriteConfig in gen-config cli

bitswap/provider.go, filecoin/retriever.go
dont_have's aren't being reported when there are no candidates for retrieval - it currently falls through at the bitswap provider and does a `blockManager.GetAwait` on a block that hasn't been fetched and the "not found" error is ignored (I've added error reporting from there too)
=> fix: properly report no candidates and dont_have

.github/actions/go-test-setup/action.yml
Requires https://github.com/filecoin-project/filecoin-ffi/pull/310
This should help not getting rate limited when getting FFI.
The error that we encountered during the tests suggests that making authenticated calls is the way to go:
```
++ curl --retry 3 --location https://api.github.com/repos/filecoin-project/filecoin-ffi/releases/tags/5d00bb4365a97890
++ echo '{"message":"API rate limit exceeded for 208.83.5.75. (But here'\''s the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}'
```
=> ci: use GITHUB_TOKEN when preparing FFI

filecoin/retriever.go
The lack of explicit timeout on query calls seems like an oversight to me. I'm not currently seeing endless connection attempts leaking in my local experiments but I imagine there's some kind of implicit timeout that's coming in to play in libp2p or some other network layer so it's probably cleaning up _eventually_. But _eventually_ is not really what we want - queries should be quick, and we should be able to drop those that don't respond quickly. This PR reuses the per-miner timeout which defaults to 1m, but we could introduce a new one just for query phase and set it even shorter. The per-miner timeout timer is reset on bytes-received so it's probably reasonable that it's reused in this way I reckon.
The deadline should get reused as a libp2p socket deadline @ …
=> feat: add timeout using deadline for RetrievalQueryToPeer calls

autoretrieve.go, bitswap/provider.go, config.go, docker-compose.yml, filecoin/activeretrievals.go, filecoin/activeretrievals_test.go, filecoin/eventrecorder/eventrecorder.go, filecoin/eventrecorder/eventrecorder_test.go, filecoin/eventrecorder/filelogserver/filelogserver.go, filecoin/retriever.go, filecoin/retrieverevents.go, go.mod, go.sum
Closes: https://github.com/application-research/autoretrieve/issues/96
I thought I'd have a go at this, I think we discussed dividing it up this way since @kylehuntsman is so keen to do https://github.com/filecoin-project/autoretrieve-deploy/issues/2 (and I'm not). This adds an HTTP PUT to `https://foo.bar/retrieval-event/~uuid~/providers/~minerid` for both successful and unsuccessful retrievals, using data I could collect at that point and seems reasonable to want. We discussed, (and I think agreed on?) flattening it to just the one endpoint and letting the server handle aggregation of uuids. The URL string before `/retrieval-event...` comes from the config, a new, optional field: `event-recorder-endpoint-url`—if not set, it's all a noop.
See the `event` struct for what's included in the …
=> feat: add HTTP event recorder reporting

blocks/randompruner.go
- pass background context to long-running pruner goroutine instead of the context parameter in the poll function
- poll the pruner immediately on startup and periodically to resolve an edge case in which the pruner would never prune when out of disk space - before, the pruner would only poll after receiving a blockstore put, but in the event that the drive was completely full already, the put would fail, and the pruner would never end up polling.
=> Pruner fixes

filecoin/eventrecorder/eventrecorder.go, filecoin/eventrecorder/eventrecorder_test.go, filecoin/retriever.go, filecoin/retrieverevents.go, go.mod, go.sum
Ref: https://github.com/application-research/filclient/pull/89 - depends on that branch's commit for filclient
This is really about cleaning up the "event" vs "state" thing now we've moved to a pure event model and not tracking state in our reporting, but it also adds `"receivedCids"` to the success case for reporting.
=> Update to use new filclient event reporter

filecoin/eventrecorder/eventrecorder.go, filecoin/eventrecorder/eventrecorder_test.go
Update the `eventReport.event` property to be `eventName`. The API is expecting `eventName`.
=> fix: update `eventReport.event` property to `eventName`

autoretrieve.go, filecoin/eventrecorder/eventrecorder.go, filecoin/eventrecorder/eventrecorder_test.go
1. Quality of life improvement by stripping off a newline from the auth token file (so you can edit it with vim and not have to care)
2. Prepend `Basic ` to the string when sending it to the server so you don't need to add that into the file, it's just the key. I don't think we want to pretend there's any other fancy scheme going on so it should be OK hardwiring this. So now the kubernetes config thing just needs to spit that secret directly into that file and it should be fine.
=> feat: strip newline from eventrecorder auth file, prepend "Basic "

filecoin/eventrecorder/eventrecorder.go
Per golang docs, http.DefaultClient.Do does not return an error for non-200 level response codes, so log it manually.
=> Log http response code failures for event recorder

autoretrieve.go, filecoin/eventrecorder/eventrecorder.go, filecoin/eventrecorder/eventrecorder_test.go, go.mod
**Problem outline:** My local instance was starting to show a _lot_ of `ErrRetrievalAlreadyRunning` errors for given CIDs that were coming in over bitswap, which is a bit weird. The log output I'm getting to my terminal is showing many thousands of "active retrievals", and querying the event log database we're now collecting was showing high numbers as well. Taking a `goroutine` pprof was showing most of the goroutines stuck in filclient's event reporter, waiting for a listener to return.
This suggests (pretty strongly), that the `EventReporter` is not freeing up the channel it maintains for events to push through to the HTTP endpoint, and they're backing up rapidly.
My local connection is not great, and I'm ~250ms round-trip delayed from us-west (and I think we're reporting to us-east, …
=> feat: increase http reporting throughput, add timeout

filecoin/eventrecorder/eventrecorder.go, filecoin/eventrecorder/eventrecorder_test.go
This moves the events api publishing from publishing one event at a time to publishing to an endpoint that accepts and array of events, with a json body of the form:
```javascript
{
"events": [
{ ~event~ },
...
]
}
```
- update event recorder to publish all pending events to each freed up publishing thread
- update publish step to send many events at once
=> Publish to array endpoint

autoretrieve.go, filecoin/eventrecorder/eventrecorder.go, filecoin/eventrecorder/eventrecorder_test.go, filecoin/retriever.go, filecoin/retrieverevents.go
Upon successful retrieval, provide a confirmation along with the reported event
that the retrieval resulted in the block being stored in the blockstore. Using
`retrievedCids` as a proxy isn't enough because it's possible (with some
non-trivial probability) that a retrieval takes place for a block that's just
been retrieved as part of a parallel retrieval, so graphsync doesn't need to
transfer any blocks.
The backstory for this is that we're seeing evidence of cases where a retrieval might look successful but doesn't result in any blocks being transferred that can't be explained by the block having already been in the blockstore. So now we get a `retrievedCids` int and a `confirmed` bool on the events. When we see a `confirmed` of `false` for a `"success"` event then it's a bug. The …
=> feat: confirm retrievals resulted in a block in the blockstore

go.mod, go.sum
has no-block-transferred failure and unique-dealid fix, among other updates
I'm running this locally, reporting events as `rvagg20220914`, will check on that in a few hours and see what to make of it
=> chore: update filclient

config.go, filecoin/retriever.go, filecoin/retriever_test.go
"paid-retrievals" config option, defaulting to "false" will turn on attempting to retrieve from deals that are non-free. Otherwise, retrieval deals that are not free will be filtered. **NOTE** this changes the default behaviour such that paid retrievals need to be opted into. This _should_ make paych errors go away.
+Other bug fixes because I wrote a test for this and found some other things along the way!
* There's a closure bug for queries where we are skipping querying some candidates! Potentially missing out on a lot of retrievals (tbh I only learned that golang doesn't capture for loop variables within scope last week)
* Per-miner configs are not using defaults in some places because we're looking directly in the `MinerConfigs` map rather than calling the `MinerConfig()` method! I …
=> feat: paid retrieval optional + bug fixes

metrics/opentelemetry.go
we're reporting queries as if they were retrievals, which is skewing the metrics badly
=> fix: unique metric name for queries

filecoin/retriever.go
Currently it's >, not >=, but when it hits retrieval-proper it does a >= so candidates can make it through this step but fail at retrieval because they are maxxed out. This now matters because we are reporting metrics on the number candidates that get through.
=> fix: filter candidates if we are _at_ or above the SP's max-concurrent

filecoin/activeretrievals.go, filecoin/retriever.go
We're seeing a lot more of these 'retrieval already running' errors than I'd expect in the logs after an instance has been running for ~half a day. This adds some additional information to the error message to help with tracking it down. Duration because if they've only been running for a few minutes then that's fine. Query/Retrieval expected & completion counts to tell us where they're held up, maybe we have missing events (like https://github.com/application-research/filclient/pull/104).
=> feat: more information on already-running errors to see if there's leaks

Makefile, scripts/autoretrieve-service/autoretrieve-register.service, scripts/autoretrieve-service/autoretrieve.service, scripts/autoretrieve-service/config.env
This makes it so that we can use autoretrieve with systemd.
Credits go to the estuary service configs which I shamelessly copy-pasted here
=> Add autoretrieve.service

metrics/opentelemetry.go
typically "timeout after 1m0s", this error occurs within autoretrieve and is not externally generated.
=> feat: add 'timeout after X' retrieval failure case

filecoin/retriever.go, metrics/opentelemetry.go
I found out a lot about query errors by looking at the database. We should record these as metrics so they show up in a dashboard.
The key insight is that many of our query errors are successful query responses that indicate a provider error.
This adds an error matching + metrics record both on actual query errors as well as query responses that indicate a provider error.
=> Query error metrics

filecoin/activeretrievals_test.go
Flake experienced @ https://github.com/application-research/autoretrieve/actions/runs/3451782684/jobs/5761244626
I think this gives us a half-millisecond resolution rather than risking hitting right on the millisecond boundary and failing.
=> fix: timestamp test resolution - allow for millisecond boundary cross

filecoin/eventrecorder/filelogserver/filelogserver.go, filecoin/retriever.go, filecoin/retriever_test.go, go.mod, go.sum
Instead of cancelling context when a timeout occurs, attempt to gracefully close the data transfer channel. Uses filclient new Async version of retrieve
=> Use async retrieval for graceful shutdown on progress timeout

filecoin/retriever.go, metrics/opentelemetry.go
Adds multiple metrics that help determine the number of requests being filtered out of each retrieval step, ie: indexer candidates, queries, and retrievals. Refactors some existing metrics and removes others that were not being used.
* **Indexer Candidates per Request**: A distribution of the number of indexer candidates we receive per request
* **Request with Indexer Candidates**: A count of the number of requests that result in non-zero candidates from the indexer
* **Request with Successful Queries**: A count of the number of requests that result in a non-zero number of successful queries from SPs
* **Successful Queries per Request**: A distribution of the number of successful queries received per request
* **Failed Retrievals per Request**: A distribution of the number of failed …
=> Add funnel filter metrics

filecoin/retriever.go
whoops, we missed this one, it's currently showing up as the same number as top-level requests coming in
=> fix: only increment requests-with-indexer-candidates when there's >0

filecoin/retriever.go
`activeRetrievals.New()` performs a "is this CID already involved in an active retrieval?" check and will return an `ErrRetrievalAlreadyRunning` if it is; move the index-filtered metric until after this point to capture this filtering in addition to the per-SP concurrency filtering.
I only realised this after watching logs while writing up details on the new funnel metrics .. It does mean we're combing two different filtering into one, but I _think_ that's OK for now. Better to not let this get lost because we lack a clear connection between "indexer candidates I can use" and "got a query response from at least one".
=> feat: move indexer-filtered metric after active-retrieval check

blocks/randompruner.go, go.mod, go.sum
Ref: https://github.com/application-research/autoretrieve/issues/142#issuecomment-1328703179
=> fix: create a new CID from a clean slice to avoid holding on to a larger memory range

go.mod, go.sum
Ref: https://github.com/ipld/go-codec-dagpb/pull/57
Ref: https://github.com/application-research/autoretrieve/issues/142#issuecomment-1328703179
#150 didn't seem to have the impact I hoped, but I want to try this to see if it does--if this doesn't have an impact then I'm not looking in the right place.
Note this is an untagged (and unmerged) version of go-codec-dagpb; I'll revert this if it has no impact and if it does then look to merging and tagging that version (although there's some discussion to be had there about whether it's the right place to do this).
=> deps: update to dag-pb version which allocates new slices

bitswap/provider.go, blocks/manager.go, blocks/manager_test.go, blocks/randompruner.go
We have chronic memory usage issues with Bedrock's autoretrieve instance. Memory allocated in go-graphsync upon receipt of new blocks makes it's way into autoretrieve's blocks.Manager.Put calls and then all the way into bitswap's peer task queue. With the default config of only one Bitswap message sending worker, this means under heavy bitswap requests, huge sets of block data are being put on the task queue as "Topic"s. They're held from the time a retrieval gets a block to the time a block gets to the top of the task queue to send over the wire. These topics, while a blank interface, were never meant to hold large objects like blocks, only intentifiers of data like cids, or other smaller items. This PR reverts them back to CIDs, like go-bitswap uses, and only reads them back off disk …
=> Don't put blocks on task queue

bitswap/provider.go, blocks/manager.go, blocks/manager_test.go
* lots of block provider debugging messages so you can see the passage of blocks through to the bitswap message
* provide a timeout error on the `AwaitBlock` callback so you can do something with it in that case (including sending a dont_have, although that might be silly 10 minutes late?)
* properly wire up the AwaitBlock timeout to the BlockManager instantiation
=> fix: block wait timeout & more provider & block debugging

main.go
log errors if autoretrieve does not start
=> Log startup error

.github/workflows/ecr-publisher.yml
I'm presuming https://github.com/filecoin-project/autoretrieve-deploy/blob/main/.github/workflows/cd.yml will pick it up from an AWS push to the cd/dev branch there?
=> feat: watch for pushes to staging branch for ecr publish
